FROM maven:3.6.3-jdk-11-slim as maven

COPY ./pom.xml ./pom.xml

COPY ./src ./src

RUN mvn dependency:go-offline -B

RUN mvn package

FROM openjdk:11-jre-slim

WORKDIR /poo

COPY --from=maven target/gestionparc-1.0-SNAPSHOT.jar ./gestionparc.jar

CMD ["java", "-jar", "./gestionparc.jar"]